### ISSUE TITLE
Release 0.6.0.pre1

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/reel#174]
`0.6.0-milestone` branch prepared for items remaining, to merge in as a group:

- [x] #164 Actor crashed! Reel::StateError [resolved by #163]: Needs '0.6.0` gem.
- [x] #153 Reel::Server::HTTPS crashes on "Errno::ECONNRESET" a2cec82
- [x] #136 ArgumentError: Data object has already been freed a2cec82
- [x] #124 From switch to if/elsif/else in Server::SSL 5e7a124
- [x] #109 Maybe implement RequestBody#empty? 1a3061c
- [x] #123 UNIX Socket support, unless jRuby server. 3bfa4f70f8ebfe327a7a73cc4078f46b43dc723f

**Comment by digitalextremist** [comment]
There's a build error taking place after a2cec82, but only under jruby. It's `Server::HTTPS` related.

**Comment by digitalextremist** [comment]
Closes #164 
Closes #153
Closes #136 
Closes #124
Closes #109 
Closes #123

All revisions leading to `.pre2` and the eventual final release will be brought into #176, especially #180 which is pending jruby/jruby#2750 being resolved by the jruby ninjas.
